
spring:
  jpa:
    hibernate:
      ddl-auto: validate

  main:
    web-application-type: none

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://mb-be:9092/mem:mbTestDb;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: importTransactionsJob

app:
  batch:
    import-transactions:
      input-resource: file:/data/transactions-source.txt
      chunk-size: 100
      lines-to-skip: 1

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,batch
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.core.io: DEBUG
    org.springframework.batch.infrastructure.item.file: DEBUG